### PR TITLE
Added public view vendor endpoints

### PR DESCRIPTION
**Pull request by chaosfinity**
Route: product/vendor lists all vendors
Route: product/vendor/{id} lists specific vendor details
Route: product/vendor/{id}/products lists vendors products the same as displayed in category products

output from route product/vendor (showing all vendors)
```javascript
{
  "vendors": [
    {
      "vendor_id": 3,
      "user_id": 2,
      "username": "user",
      "name": "Test Vendor",
      "thumb": null,
      "telephone": "5555551234",
      "fax": "",
      "company": "",
      "description": "Test",
      "email": "user@example.com",
      "firstname": "John",
      "lastname": "Doe",
      "address": {
        "address_1": "1234 Awesome Drive",
        "address_2": "",
        "city": "Kansas City",
        "postcode": "64161",
        "country": {
          "country_id": "223",
          "name": "United States",
          "iso_code_2": "US",
          "iso_code_3": "USA",
          "address_format": "{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city}, {zone} {postcode}\r\n{country}",
          "postcode_required": "0",
          "status": "1"
        },
        "zone": {
          "zone_id": "3648",
          "country_id": "223",
          "name": "Missouri",
          "code": "MO",
          "status": "1"
        }
      },
      "accept_paypal": "0",
      "accept_cheques": "0",
      "accept_bank_transfer": "0",
      "sort_order": "0"
    }
  ]
}
```

### CODE REVIEW

**Comment by chaosfinity** [comment]
All vendor view templates for vendors on the public site are stubs created from manufacture and category views just to make the api work for now.

**Comment by chaosfinity** [comment]
One more thing,
The front end pages are available at
```
GET: product/vendor   -   Displays list of vendors
GET: product/vendor/info?vendor_id={id}   -  Displays vendor name description and products
```

**Comment by david-r-edgar** [comment]
a question here - it's arguable and perhaps not really crucial, but the API docs suggest (http://oc2-demo.opencartapi.com/docs/v1/Custom_API_Methods.html) that the 'base' directory files are only for the original API extension, and custom methods should be implemented in the main directory.
I realise vendor_base.php is new so there's not likely to be a conflict, but I just wondered if it would be cleaner to keep all the implementation out of /base ?

**Comment by chaosfinity** [comment]
My thinking was to use the main directory file as the route file, so product/vendor maps to index and product/vendor/{id}/products maps to the products method and to keep the messy logic in the base file so the main directory can easily be read as a route controller and not as a data transformer

**Pull request merged**
